# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: cards-deployment
deploymentLabel: cards

replicaCount: 2

image:
  repository: raj120986/easybank
  tag: cards

containerPort: 9090

service:
  type: LoadBalancer
  port: 9090
  targetPort: 9090

config_enabled: true
profile_enabled: true
eureka_enabled: true