# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: eurekaserver-deployment
deploymentLabel: eurekaserver

replicaCount: 1

image:
  repository: raj120986/easybank
  tag: eurekaserver

containerPort: 6060

service:
  type: LoadBalancer
  port: 6060
  targetPort: 6060

config_enabled: true
profile_enabled: true
eureka_enabled: false