apiVersion: v1
kind: ConfigMap
metadata:
  name: eazybank-configmap
data:
  SPRING_PROFILES_ACTIVE: dev
  SPRING_CONFIG_IMPORT: configserver:http://configserver-service:8080/
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver-service:6060/eureka/
