# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: accounts-deployment
deploymentLabel: accounts

replicaCount: 2

image:
  repository: raj120986/easybank
  tag: accounts

containerPort: 8070

service:
  type: LoadBalancer
  port: 8070
  targetPort: 8070

config_enabled: true
profile_enabled: true
eureka_enabled: true